---
apiVersion: apps/v1
kind: DaemonSet
metadata:
   name: https-version
   labels:
      type: webserver
spec: 
    selector:
          matchLabels:
                type: webserver
    template:
        metadata:
              name: httpd-pod
              labels: 
                  type: webserver


        spec:
            containers: 
              - name: my-httpd
                image: httpd
                ports:
                    - containerPort: 80
                      hostPort: 8888
...                        
