---
apiVersion: v1
kind: Pod
metadata: 
    name: mysql-pod
    labels:
          type: db
          author: prasad
spec:
    containers:
          - name: mysqldb
            image: mysql
            env :
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                        secretKeyRef:
                              name: mysql-secret
                              key: a
...  
