---
apiVersion: v1
kind: Pod
metadata: 
    name: postgres-pod
    labels:
       type: db
       author: prasad
spec:
    containers:
        - name: mydb
          image: postgres
          env: 
            - name: POSTGRES_PASSWORD
              value: prasad
            - name: POSTGRES_USER
              value: prasad
            - name: POSTGRE_DB
              value: mydb
...                
