---
apiVersion: v1
kind: Service
metadata:
    name: httpd-service
    labels:
        author: prasad
spec:
    type: NodePort
    ports:
        - targetPort: 80
          port: 80
    selector:
        type: webserver
        author: prasad
...          

