---
apiVersion: v1
kind: Service
metadata: 
    name: voting-app-service
    labels:
       author: prasad
spec: 
    type: LoadBalancer
    ports:
        - targetPort: 80
          port: 80
          nodePort: 30008
    selector:
        name: votting-app
...          
